export const TOKENS = {
  DATABASE: Symbol('DATABASE'),
  DOCKER_CLIENT: Symbol('DOCKER_CLIENT'),
  GIT_SERVICE: Symbol('GIT_SERVICE'),
  REPO_REGISTRY: Symbol('REPO_REGISTRY'),
  GITHUB_APP_SERVICE: Symbol('GITHUB_APP_SERVICE'),
  GITHUB_DISCOVERY_SERVICE: Symbol('GITHUB_DISCOVERY_SERVICE'),
  GITHUB_IMPORT_SERVICE: Symbol('GITHUB_IMPORT_SERVICE'),
  CONTAINER_SERVICE: Symbol('CONTAINER_SERVICE'),
  VOLUME_SERVICE: Symbol('VOLUME_SERVICE'),
  SESSION_ORCHESTRATOR: Symbol('SESSION_ORCHESTRATOR'),
  IDLE_TIMEOUT_MANAGER: Symbol('IDLE_TIMEOUT_MANAGER'),
  ANTHROPIC_API_KEY: Symbol('ANTHROPIC_API_KEY'),
} as const;
